### ISSUE TITLE
Питон детектед

### ISSUE THREAD

**Issue by progzone122** [Dallleworthy/Minecraft-Laucnher#1]
Срочно нужно переписать на расте

**Comment by progzone122** [comment]
Так будет растов, да

**Comment by Dallleworthy** [comment]
> Срочно нужно переписать на расте

**Comment by Dallleworthy** [comment]
Уже сегодня в 23:59 будет Раст версия.
Если вы не обнаружили Раст версию, перечитайте это сообщение снова!
